# Generated by Django 4.0 on 2022-01-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adddatamod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('fee', models.IntegerField()),
                ('assignment1', models.IntegerField()),
                ('assignment2', models.IntegerField()),
                ('assignment3', models.IntegerField()),
                ('assignment4', models.IntegerField()),
            ],
        ),
    ]
