# Generated by Django 4.0 on 2022-01-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddatamod',
            name='assignment1',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adddatamod',
            name='assignment2',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adddatamod',
            name='assignment3',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adddatamod',
            name='assignment4',
            field=models.IntegerField(max_length=100),
        ),
    ]
